USE DATABASE HEALTH_APP;

GRANT ROLE dev_sec_ops_role to USER XXX;

--- Droits donnés par l'admin

CREATE ROLE IF NOT EXISTS dev_sec_ops_role;
GRANT USAGE ON DATABASE health_app TO ROLE dev_sec_ops_role;
GRANT CREATE DATABASE, CREATE USER, CREATE ROLE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE dev_sec_ops_role WITH GRANT OPTION;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE dev_sec_ops_role WITH GRANT OPTION;

USE SECONDARY ROLES NONE;